events {
    worker_connections 1024;
}

http {
    # VULNERABILITY 3: Missing Security Headers (HSTS, X-Frame-Options)
    
    upstream keycloak_backend {
        server keycloak:8080;
    }

    upstream bff_backend {
        server bff-gateway:80;
    }

    server {
        listen 80;
        server_name localhost;

        # VULNERABILITY 4: Missing X-Forwarded-Proto
        # Missing proxy_set_header X-Forwarded-Proto $scheme;

        # VULNERABILITY 5: Unprotected Admin Console
        # Missing location block to block /auth/admin
        
        location /auth {
            proxy_pass http://keycloak_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /employee {
            proxy_pass http://bff_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
