version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev --metrics-enabled=true
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
      - 9000:9000
    networks:
      - my_monitor_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my_monitor_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - my_monitor_network

networks:
  my_monitor_network:
    driver: bridge
