events {}

http {
    upstream keycloak_cluster {
        # Session Affinity - Khách Dính Vào 1 Đáy Máy Mạch OIDC Kẽ
        ip_hash;
        
        server kc_node_1:8080 max_fails=3 fail_timeout=15s;
        server kc_node_2:8080 max_fails=3 fail_timeout=15s;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://keycloak_cluster;
            
            # Khởi Móng Xé Cấu Header Cho Edge Proxy Nhận Lệnh Đẩy Ảo Sóng Khung
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # Bơm Giả Lập Mạng SSL Đáy Ảo Edge Bọc
            proxy_set_header X-Forwarded-Proto $scheme; 
        }
    }
}
