version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Bật tính năng passkeys (passkeys đã trở thành chuẩn mặc định, nhưng cứ khai báo để chắc chắn)
      KC_FEATURES: passkeys
    ports:
      - "8080:8080"
    volumes:
      - keycloak_auth_data:/opt/keycloak/data
    networks:
      - kc_auth_network

volumes:
  keycloak_auth_data:

networks:
  kc_auth_network:
    driver: bridge
