version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: keycloak-db-chapter22
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak-network-22

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak-server-chapter22
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start-dev
      - --http-port=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network-22

networks:
  keycloak-network-22:
    driver: bridge
